repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: sanitize-unicode
        name: sanitize unicode check
        entry: python tools/sanitize_unicode.py --check
        language: system
        pass_filenames: false
        files: "\.(py|toml|ya?ml|md)$"
